#' downloadStravaAll
#'
#' This function downloads all of the Strava activities from the pre-defined list
#'
#' @return a list of all the Strava activity ID's
#' it has columns lat, lon, snodep and present.
#' present is 0 for bare ground, 1 for snow (no data are excluded))

downloadStravaAll <- function() {
  
  # get the list of the Strava activities
  activity_IDs <- c()
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/cheb_WinterSport_1.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/cheb_WinterSport_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/cheb_WinterSport_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/cheb_WinterSport_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/cheb_Nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/cheb_Nordic_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/cheb_Nordic_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/cheb_Backcountry_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/cheb_Backcountry_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/cheb_Backcountry_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/cheb_bezky_1.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_WinterSport_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_WinterSport_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_WinterSport_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_WinterSport_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_Nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_Nordic_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_Nordic_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_Nordic_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_Backcountry_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_Backcountry_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_Backcountry_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_bezky_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_bezky_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_lyze_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kv_lyze_2.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_WinterSport_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_WinterSport_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_WinterSport_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_WinterSport_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_Nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_Nordic2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_Nordic3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_Nordic4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_Backcountry1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_Backcountry2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_Backcountry3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_bezky1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_bezky2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_lyze1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/plz_lyze2.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_WinterSport_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_WinterSport_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_WinterSport_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_WinterSport_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_Nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_Nordic_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_Nordic_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_Backcountry_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_Backcountry_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_Backcountry_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_Backcountry_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_bezky_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_bezky_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_bezky_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_lyze_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/kvilda_lyze_2.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/praha_winter_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/praha_winter_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/praha_winter_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/praha_nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/praha_nordic_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/praha_nordic_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/praha_nordic_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/praha_backcountry_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/praha_backcountry_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/praha_bezky_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/praha_bezky_2.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_winter_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_winter_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_winter_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_winter_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_nordic_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_nordic_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_nordic_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_backcountry_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_backcountry_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_bezky_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_bezky_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_lyze_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zinn_lyze_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/praha_bezky_2.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jist_winter_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jist_winter_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jist_winter_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jist_nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jist_nordic_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jist_nordic_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jist_nordic_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jist_backcountry_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jist_backcountry_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jist_backcountry_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jist_bezky_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jist_bezky_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jist_lyze_1.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_winter_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_winter_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_winter_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_winter_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_nordic_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_nordic_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_nordic_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_backcountry_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_backcountry_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_backcountry_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_backcountry_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_bezky_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_bezky_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_bezky_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_bezky_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_lyze_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jiz_lyze_2.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_winter_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_winter_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_winter_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_winter_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_nordic_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_nordic_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_nordic_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_backcountry_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_backcountry_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_backcountry_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_backcountry_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_bezky_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_bezky_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_bezky_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_bezky_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/vrchlabi_lyze_1.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zdob_nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zdob_nordic_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zdob_nordic_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zdob_nordic_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zdob_backcountry_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zdob_backcountry_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zdob_backcountry_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zdob_backcountry_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zdob_bezky_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/zdob_bezky_2.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_winter_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_winter_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_winter_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_winter_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_nordic_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_nordic_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_nordic_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_backcountry_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_backcountry_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_backcountry_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_backcountry_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_bezky_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_bezky_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_bezky_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/svra_lyze_1.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_winter_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_winter_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_winter_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_winter_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_nordic_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_nordic_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_nordic_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_backcountry_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_backcountry_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_backcountry_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_backcountry_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_bezky_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_bezky_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_bezky_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_lyze_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/olom_lyze_2.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_winter_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_winter_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_winter_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_winter_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_nordic_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_nordic_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_nordic_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_backcountry_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_backcountry_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_backcountry_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_backcountry_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_bezky_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_bezky_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_bezky_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_lyze_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/ostr_lyze_2.html"))
  
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_winter_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_winter_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_winter_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_winter_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_nordic_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_nordic_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_nordic_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_nordic_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_backcountry_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_backcountry_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_backcountry_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_backcountry_4.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_bezky_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_bezky_2.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_bezky_3.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_lyze_1.html"))
  activity_IDS <- c(activity_IDs, getStravaActivityIDs("lists/jese_lyze_2.html"))
}