##############################################
# STRAVA GPX Exporter Library                #
##############################################

library(httr)
library(sp)
library(rgdal)
library(XML)

parseTcx <- function(my_file) {
  doc <- xmlParse(my_file)
  nodes <- getNodeSet(doc, "//ns:Trackpoint", "ns")
  mydf  <- plyr::ldply(nodes, as.data.frame(xmlToList))
  names(mydf) <- c("time", "lat", "lon", "elev", "dist")
  mydf$lat <- as.numeric(as.character(mydf$lat))
  mydf$lon <- as.numeric(as.character(mydf$lon))
  coordinates(mydf) <- ~lon+lat
  plot(mydf, pch=16, col="red")
  return(mydf)
}

############################################################
getActivity <- function(activity_id) {
  #activity_id <- 269583360
  url <- paste("http://raceshape.com/strava.export.php?ride=",
               activity_id, "&type=tcx", sep="")
  my_file <- paste(activity_id, ".tcx", sep="")
  GET(url, write_disk(my_file, overwrite=TRUE))
  Sys.sleep(30)
  GET(url, write_disk(my_file, overwrite=TRUE))
  #track <- parseTcx(my_file)
}
############################################################

############################################################
# HTML parsing for STRAVA activities
############################################################
#activities_file <- download.file(destfile="activities.html", 
#url="https://www.strava.com/activities/search?activity_type=NordicSki&city=Prague&country=Czech+Republic&distance_end=200&distance_start=0&elev_gain_end=15000&elev_gain_start=0&keywords=&lat_lng=50.0755381%2C14.43780049999998&location=Praha&page=1&state=Hlavn%C3%AD+m%C4%9Bsto+Praha&time_end=10.0&time_start=0.0&type=&utf8=%E2%9C%93")

download_activities <- function (activities_html) {
  html.raw <- htmlTreeParse(activities_html, useInternalNodes=TRUE)
  html.parse <- xpathApply(html.raw, "//a", xmlAttrs)
  activ.parse <- grep('*/activities/[0-9]+', unlist(html.parse), value=TRUE)
  
  i <- 1
  for (i in 1: length(activ.parse)) {
    activ.parse[i]
    activity_id <- as.numeric(substr(activ.parse[i], 13, 23))
    activity_file <- paste(activity_id, ".tcx", sep="")
    if (!file.exists(activity_file)) {
      getActivity(activity_id)
    }
  }
}

download_activities("lists/cheb_WinterSport_1.html")
download_activities("lists/cheb_WinterSport_2.html")
download_activities("lists/cheb_WinterSport_3.html")
download_activities("lists/cheb_Nordic_1.html")
download_activities("lists/cheb_Nordic_2.html")
download_activities("lists/cheb_Nordic_3.html")
download_activities("lists/cheb_Backcountry_1.html")
download_activities("lists/cheb_Backcountry_2.html")
download_activities("lists/cheb_Backcountry_3.html")
download_activities("lists/cheb_bezky_1.html")

download_activities("lists/kv_WinterSport_1.html")
download_activities("lists/kv_WinterSport_2.html")
download_activities("lists/kv_WinterSport_3.html")
download_activities("lists/kv_WinterSport_4.html")
download_activities("lists/kv_Nordic_1.html")
download_activities("lists/kv_Nordic_2.html")
download_activities("lists/kv_Nordic_3.html")
download_activities("lists/kv_Nordic_4.html")
download_activities("lists/kv_Backcountry_1.html")
download_activities("lists/kv_Backcountry_2.html")
download_activities("lists/kv_Backcountry_3.html")
download_activities("lists/kv_bezky_1.html")
download_activities("lists/kv_bezky_2.html")
download_activities("lists/kv_lyze_1.html")
download_activities("lists/kv_lyze_2.html")

download_activities("lists/plz_WinterSport_1.html")
download_activities("lists/plz_WinterSport_2.html")
download_activities("lists/plz_WinterSport_3.html")
download_activities("lists/plz_WinterSport_4.html")
download_activities("lists/plz_Nordic_1.html")
download_activities("lists/plz_Nordic2.html")
download_activities("lists/plz_Nordic3.html")
download_activities("lists/plz_Nordic4.html")
download_activities("lists/plz_Backcountry1.html")
download_activities("lists/plz_Backcountry2.html")
download_activities("lists/plz_Backcountry3.html")
download_activities("lists/plz_bezky1.html")
download_activities("lists/plz_bezky2.html")
download_activities("lists/plz_lyze1.html")
download_activities("lists/plz_lyze2.html")

download_activities("lists/kvilda_WinterSport_1.html")
download_activities("lists/kvilda_WinterSport_2.html")
download_activities("lists/kvilda_WinterSport_3.html")
download_activities("lists/kvilda_WinterSport_4.html")
download_activities("lists/kvilda_Nordic_1.html")
download_activities("lists/kvilda_Nordic_2.html")
download_activities("lists/kvilda_Nordic_3.html")
download_activities("lists/kvilda_Backcountry_4.html")
download_activities("lists/kvilda_Backcountry_1.html")
download_activities("lists/kvilda_Backcountry_2.html")
download_activities("lists/kvilda_Backcountry_3.html")
download_activities("lists/kvilda_bezky_1.html")
download_activities("lists/kvilda_bezky_2.html")
download_activities("lists/kvilda_bezky_3.html")
download_activities("lists/kvilda_lyze_1.html")
download_activities("lists/kvilda_lyže_2.html")

download_activities("lists/praha_winter_1.html")
download_activities("lists/praha_winter_2.html")
download_activities("lists/praha_winter_3.html")
download_activities("lists/praha_nordic_1.html")
download_activities("lists/praha_nordic_2.html")
download_activities("lists/praha_nordic_3.html")
download_activities("lists/praha_nordic_4.html")
download_activities("lists/praha_backcountry_1.html")
download_activities("lists/praha_backcountry_2.html")
download_activities("lists/praha_bezky_1.html")
download_activities("lists/praha_bezky_2.html")

download_activities("lists/zinn_winter_1.html")
download_activities("lists/zinn_winter_2.html")
download_activities("lists/zinn_winter_3.html")
download_activities("lists/zinn_winter_4.html")
download_activities("lists/zinn_nordic_1.html")
download_activities("lists/zinn_nordic_2.html")
download_activities("lists/zinn_nordic_3.html")
download_activities("lists/zinn_nordic_4.html")
download_activities("lists/zinn_backcountry_1.html")
download_activities("lists/zinn_backcountry_2.html")
download_activities("lists/zinn_bezky_1.html")
download_activities("lists/zinn_bezky_2.html")
download_activities("lists/zinn_lyze_1.html")
download_activities("lists/zinn_lyze_2.html")
download_activities("lists/praha_bezky_2.html")

download_activities("lists/jist_winter_1.html")
download_activities("lists/jist_winter_2.html")
download_activities("lists/jist_winter_3.html")
download_activities("lists/jist_nordic_1.html")
download_activities("lists/jist_nordic_2.html")
download_activities("lists/jist_nordic_3.html")
download_activities("lists/jist_nordic_4.html")
download_activities("lists/jist_backcountry_1.html")
download_activities("lists/jist_backcountry_2.html")
download_activities("lists/jist_backcountry_3.html")
download_activities("lists/jist_bezky_1.html")
download_activities("lists/jist_bezky_2.html")
download_activities("lists/jist_lyze_1.html")

download_activities("lists/jiz_winter_1.html")
download_activities("lists/jiz_winter_2.html")
download_activities("lists/jiz_winter_3.html")
download_activities("lists/jiz_winter_4.html")
download_activities("lists/jiz_nordic_1.html")
download_activities("lists/jiz_nordic_2.html")
download_activities("lists/jiz_nordic_3.html")
download_activities("lists/jiz_nordic_4.html")
download_activities("lists/jiz_backcountry_1.html")
download_activities("lists/jiz_backcountry_2.html")
download_activities("lists/jiz_backcountry_3.html")
download_activities("lists/jiz_backcountry_4.html")
download_activities("lists/jiz_bezky_1.html")
download_activities("lists/jiz_bezky_2.html")
download_activities("lists/jiz_bezky_3.html")
download_activities("lists/jiz_bezky_4.html")
download_activities("lists/jiz_lyze_1.html")
download_activities("lists/jiz_lyze_2.html")

download_activities("lists/vrchlabi_winter_1.html")
download_activities("lists/vrchlabi_winter_2.html")
download_activities("lists/vrchlabi_winter_3.html")
download_activities("lists/vrchlabi_winter_4.html")
download_activities("lists/vrchlabi_nordic_1.html")
download_activities("lists/vrchlabi_nordic_2.html")
download_activities("lists/vrchlabi_nordic_3.html")
download_activities("lists/vrchlabi_nordic_4.html")
download_activities("lists/vrchlabi_backcountry_1.html")
download_activities("lists/vrchlabi_backcountry_2.html")
download_activities("lists/vrchlabi_backcountry_3.html")
download_activities("lists/vrchlabi_backcountry_4.html")
download_activities("lists/vrchlabi_bezky_1.html")
download_activities("lists/vrchlabi_bezky_2.html")
download_activities("lists/vrchlabi_bezky_3.html")
download_activities("lists/vrchlabi_bezky_4.html")
download_activities("lists/vrchlabi_lyze_1.html")

download_activities("lists/zdob_nordic_1.html")
download_activities("lists/zdob_nordic_2.html")
download_activities("lists/zdob_nordic_3.html")
download_activities("lists/zdob_nordic_4.html")
download_activities("lists/zdob_backcountry_1.html")
download_activities("lists/zdob_backcountry_2.html")
download_activities("lists/zdob_backcountry_3.html")
download_activities("lists/zdob_backcountry_4.html")
download_activities("lists/zdob_bezky_1.html")
download_activities("lists/zdob_bezky_2.html")

download_activities("lists/svra_winter_1.html")
download_activities("lists/svra_winter_2.html")
download_activities("lists/svra_winter_3.html")
download_activities("lists/svra_winter_4.html")
download_activities("lists/svra_nordic_1.html")
download_activities("lists/svra_nordic_2.html")
download_activities("lists/svra_nordic_3.html")
download_activities("lists/svra_nordic_4.html")
download_activities("lists/svra_backcountry_1.html")
download_activities("lists/svra_backcountry_2.html")
download_activities("lists/svra_backcountry_3.html")
download_activities("lists/svra_backcountry_4.html")
download_activities("lists/svra_bezky_1.html")
download_activities("lists/svra_bezky_2.html")
download_activities("lists/svra_bezky_3.html")
download_activities("lists/svra_lyze_1.html")

download_activities("lists/olom_winter_1.html")
download_activities("lists/olom_winter_2.html")
download_activities("lists/olom_winter_3.html")
download_activities("lists/olom_winter_4.html")
download_activities("lists/olom_nordic_1.html")
download_activities("lists/olom_nordic_2.html")
download_activities("lists/olom_nordic_3.html")
download_activities("lists/olom_nordic_4.html")
download_activities("lists/olom_backcountry_1.html")
download_activities("lists/olom_backcountry_2.html")
download_activities("lists/olom_backcountry_3.html")
download_activities("lists/olom_backcountry_4.html")
download_activities("lists/olom_bezky_1.html")
download_activities("lists/olom_bezky_2.html")
download_activities("lists/olom_bezky_3.html")
download_activities("lists/olom_lyze_1.html")
download_activities("lists/olom_lyze_2.html")

download_activities("lists/ostr_winter_1.html")
download_activities("lists/ostr_winter_2.html")
download_activities("lists/ostr_winter_3.html")
download_activities("lists/ostr_winter_4.html")
download_activities("lists/ostr_nordic_1.html")
download_activities("lists/ostr_nordic_2.html")
download_activities("lists/ostr_nordic_3.html")
download_activities("lists/ostr_nordic_4.html")
download_activities("lists/ostr_backcountry_1.html")
download_activities("lists/ostr_backcountry_2.html")
download_activities("lists/ostr_backcountry_3.html")
download_activities("lists/ostr_backcountry_4.html")
download_activities("lists/ostr_bezky_1.html")
download_activities("lists/ostr_bezky_2.html")
download_activities("lists/ostr_bezky_3.html")
download_activities("lists/ostr_lyze_1.html")
download_activities("lists/ostr_lyze_2.html")

download_activities("lists/jese_winter_1.html")
download_activities("lists/jese_winter_2.html")
download_activities("lists/jese_winter_3.html")
download_activities("lists/jese_winter_4.html")
download_activities("lists/jese_nordic_1.html")
download_activities("lists/jese_nordic_2.html")
download_activities("lists/jese_nordic_3.html")
download_activities("lists/jese_nordic_4.html")
download_activities("lists/jese_backcountry_1.html")
download_activities("lists/jese_backcountry_2.html")
download_activities("lists/jese_backcountry_3.html")
download_activities("lists/jese_backcountry_4.html")
download_activities("lists/jese_bezky_1.html")
download_activities("lists/jese_bezky_2.html")
download_activities("lists/jese_bezky_3.html")
download_activities("lists/jese_lyze_1.html")
download_activities("lists/jese_lyze_2.html")
